#include <stdio.h>
#include "findmp.h"
#include "../io/io.h"

int main(int argc, char** argv) {
	/*char* seg_A="GAATTTATCAATGGTATCAGGAGTCATAGGAGTGTCATTGAACTGCTCATTAGCAAGCTCAAAAAAGCACTTCATGCCCTGGAAGGGACCTTTAAGTTTTTCCAGAAGCAACCAACCGCC";
	char* seg_B="TTGTTTTCTGATGATGTCAGTGGCATGTTGTCTGTTTCTTTGAACTCTGATCTTAATTTGATCCACTGTGAAAAGATAAGATGGTGGTAAGTATATGTAATGTGCATGTGGTGCAAGACA";
	char* readsF[]={"AATGGTATCAGGAGTCATAGGAGTGTCATT","AGTGTCATTGAACTGCTCATTAGCAAGCTCAAA"};
	char* readsR[]={"AATGTGCATGTGGTGCAAGACA","AATGTGCATGTGGTGCAAGACA"};
	printf("Found %d\n",findmp(seg_A,seg_B,readsF,readsR,2,15));
	*/ char **reads1FW;
	char **reads1RV;
	char **reads2FW;
	char **reads2RV;
	int num_reads;
        reads1FW=get_reads("/tmp/1",&num_reads,&reads1RV);
        reads2FW=get_reads("/tmp/2",&num_reads,&reads2RV);
/*
19310/2+:<0,90568,1>
19310/1-:<0,91051,0>
*/	
	char* seg_A="GTTCAGGTAACGCACGATGGCAGAGTGGTGGAAATAGACCAGGTGCTTGAATTCGCGCACCTCGCCGCCGTGTTCGGGCGAGATGACAGTGCGAAACAGGTGGTTGTAGATGGGTTTGGTCTCCTCCTCATTGAGACTGTCTACCAGAGCCGACAGCGGGATGGGCTGGTGAGTGTGTAGGTAGTGCGCGAGGTTCAGGACGTCGTTATTGACCACGAACACCGGCGCCACGCGCTGAGAGTCAGTGCACTTTTGGGTCTGTAAACAGAAGTAAACTAGGTTGGAGGCGTGGTGTTTGACCAGTAAGGGGAACACACAGTGTTCAGACACAGATTTTGAAAGCACGTTAGCGACTATATGAGCAGAATCATACTCTGTCGCGAACAGAACCAGCGTCATTGTCAGTGAAGGATGGACCTGGCGCGGCGCCTTTGGGGTTTTCTCAGCTGCCAGCGGCGAGCTTCAGCTGGAGCAGACTATGTGCTGCTACGGCCCAGCGAAGATGTGAACATGCAGGAGATGCAGTCCTTTTTTGAGGAGAACTTTGGGACGCTGGGGATCACGCCCGAGGATTTGAAGGCGTTTGCTAATGACGATGAAGTGACGAAGCACTTACTCAAGCTTATTCCTTTGTATCGGCACTGTCAGGTCAAGTGTCGAATGCTGCAGGACTACCTCGCGGATAGTTGTCAGCCGCATACGCGGCCTGCCGCCGAAGTAGAGAATCAAAAATCGCAGCGTATTATGCAGGCTTTAGACGTGATGATTTTAAAGTTGGTGGTGGGCGAGTTCTCCATGTCTGAGGACGATACTTTGGAGGTCTTGCTCAATAAGTTCTCTACAGATCAGGTGGCACTCTGTGAGGTGCAGAAGGTTATGGGCCTGGTGGACATGGATTGCGATCAGAGTACCTCAATTCTGGATGCTGCAGCAGCAGCAGCGGCTGCCGCCAATGCAGAAAACTGTTCTGCGGTAGCTGAAGGCGGCATCGATGAAAGCGT";
	char* seg_B="TTTTGGCAATGATTCCGCACCCGCCTCAGGAAGAACTGCCTGTTGTGGAAGAGGTGTGCCCCCCTATACCAATGCCGCCTC";
	findmp(seg_A,seg_B,reads1FW,reads2RV,num_reads,18);
	findmp(seg_A,seg_B,reads2FW,reads1RV,num_reads,18);
	findmp(seg_A,seg_B,reads1FW,reads2FW,num_reads,18);
	findmp(seg_A,seg_B,reads1RV,reads2RV,num_reads,18);
	findmp(seg_A,seg_B,reads2RV,reads1FW,num_reads,18);
	findmp(seg_A,seg_B,reads1RV,reads2FW,num_reads,18);
	
	return 0;
}
